### ISSUE TITLE
Update JS implementation to ES6 JavaScript Modules

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#5]
Hello,
I found legacy mixed JavaScript code in PHP files.

Please consider updating the implementation to use JavaScript Modules with ES6.

For guidance, you can refer to the following documentation:
[Moodle JavaScript Guide](https://moodledev.io/docs/4.2/guides/javascript)
[JavaScript Modules in Moodle](https://moodledev.io/docs/4.2/guides/javascript/modules)
This will ensure better compatibility with modern Moodle standards.

![image](https://github.com/user-attachments/assets/b1a637c7-cc2d-4373-ad06-cdcb89818421)
![image](https://github.com/user-attachments/assets/3f008116-438e-4313-969e-d200e220d4a0)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

Thank you for the advice. I have implemented it so that all necessary data are collected within the foreach loop. Afterwards, a separate script is called via js_call_amd to generate the messages.
The release you will see in version 1.1

![image](https://github.com/user-attachments/assets/ce32903a-9809-49eb-b9b4-04404929ec4c)


Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version
